<a href="https://colab.research.google.com/github/sunjinnn/Blockchain2025/blob/main/25_10_16_%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

fish = pd.read_csv('http://bit.ly/fish_csv_data')
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)



#여기서부터는 스케일링
ss = StandardScaler()
ss.fit(train_input) #학습 셋 만들어줌
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

print(lr.predict(train_bream_smelt[:5]))
print(lr.classes_)
print(np.round(lr.predict_proba(train_bream_smelt[:5]), decimals=3))

print(lr.coef_, lr.intercept_) #가중치를 찍어보자

decisions = lr.decision_function(train_bream_smelt[:5])
print(np.round(decisions, decimals=2))

from scipy.special import expit
print(expit(decisions))

# print(train_target) #여러가지 섞여있음
# print(target_bream_smelt) #bream이랑 smelt 밖에 없음


# kn.fit(train_scaled, train_target)
# print(kn.predict(test_scaled[:5])) #여기까지가 예측
# print(test_target[:5]) #정답! 예측한 거 중에 1개 틀림

# print(kn.classes_)
# proba = kn.predict_proba(test_scaled[:5])
# print(np.round(proba, decimals=1))

# print(fish_input.head())
# print(fish_target.head()) #to_numpy로 해줬기 때문에 오류가 난다

# print(fish['Species'])
# print(fish.head()) #pandas가 있어야만 사용 가능함

['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']
['Bream' 'Smelt']
[[0.998 0.002]
 [0.027 0.973]
 [0.995 0.005]
 [0.986 0.014]
 [0.998 0.002]]
[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]
[-6.03  3.57 -5.27 -4.24 -6.06]
[0.00239993 0.97262675 0.00513614 0.01414953 0.00232581]
